// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfKQL1s5UVAFtyatwLY2TP7FXdEdFNhjc',
    appId: '1:308620194845:web:3feceee4add598072082f4',
    messagingSenderId: '308620194845',
    projectId: 'fir-zakatapp',
    authDomain: 'fir-zakatapp.firebaseapp.com',
    storageBucket: 'fir-zakatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6FuFHLTJdrUcafyecPwwQw2WpMQ48kI',
    appId: '1:308620194845:android:9744d924c1d580102082f4',
    messagingSenderId: '308620194845',
    projectId: 'fir-zakatapp',
    storageBucket: 'fir-zakatapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3YX713Wt5-Os4h4xCz6NEgKxPfMXRoHo',
    appId: '1:308620194845:ios:b1a30c495f706b232082f4',
    messagingSenderId: '308620194845',
    projectId: 'fir-zakatapp',
    storageBucket: 'fir-zakatapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3YX713Wt5-Os4h4xCz6NEgKxPfMXRoHo',
    appId: '1:308620194845:ios:b1a30c495f706b232082f4',
    messagingSenderId: '308620194845',
    projectId: 'fir-zakatapp',
    storageBucket: 'fir-zakatapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfKQL1s5UVAFtyatwLY2TP7FXdEdFNhjc',
    appId: '1:308620194845:web:caa3a51a1339a69e2082f4',
    messagingSenderId: '308620194845',
    projectId: 'fir-zakatapp',
    authDomain: 'fir-zakatapp.firebaseapp.com',
    storageBucket: 'fir-zakatapp.firebasestorage.app',
  );
}
